baseUrl=https://sport-reservation-2-api-bootcamp.do.dibimbing.id/api/v1
email=syukran@gmail.com
password=syukran123
#API (GraphQL):
url=https://lmsb2b.do.dibimbing.id/graphql
#Credentials:
usernameGraphQL=b2bserveruser
passwordGraphQL=ENAcA3Sog22681sAKvih8KkpDKvF2aQ6
#?Web Application Under Test:
webUrl=https://lms-b2b.do.dibimbing.id/dibimbingqa/login
#Credentials:
emailWeb=arwendymelyn@dibimbing.id
passwordWeb=s2et9bh6l
companyId=811637b1-9989-4d45-a9f5-220c5f2354f7
companySlug=companySlug
